version: '3.7'
services:
    app1:
        build: app1
    nginx:
        container_name: nginx
        build: nginx
        ports:
            - 5000:80
        depends_on:
           - app1
    db:
        image: redis
        command: redis-server --appendonly yes
        volumes:
            - redis_storage:/data
volumes:
    redis_storage: